still checking requests requirement

diff --git a/mrf_proj b/mrf_proj
--- a/mrf_proj
+++ b/mrf_proj
@@ -48,9 +48,9 @@ if [ $1 == setup ] ; then
     echo "setting up third party statics"
 
     # check if request module installed
-    python -c "import request"
+    python -c "import requests"
 
-    [ $? -ne 0 ] && echo "python request module not found : please install via pip" && exit -1
+    [ $? -ne 0 ] && echo "python requests module not found : please install" && exit -1
 
     python ${MRFBUS_HOME}/land/thirdparty_static.py
 
